# Generated by Django 2.2.8 on 2020-01-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_role',
            field=models.CharField(choices=[('SUPPLIER', 'SUPPLIER'), ('COMPANY', 'SUPPLIER'), ('ADMIN', 'ADMIN'), ('EMPLOYEE', 'EMPLOYEE')], max_length=50),
        ),
    ]
