# Generated by Django 2.2.8 on 2020-01-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200116_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job_role',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
